// Put your Flickr API key here...
public static const FLICKR_API_KEY : String = ""

// Put your Djakota resolver URL here...
public static const DJAKOTA_RESOLVER_URL : String = "http://localhost:8080/adore-djatoka/resolver"